### ISSUE TITLE
parameter retries  and sendat by messages

### ISSUE THREAD

**Issue by tubssp** [esendex/esendex-php-sdk#7]
Hello there,

I've looked at under http://developers.esendex.com/APIs/REST-API/messagedispatcher the "raw" API.
There is the parameter "retries" and "sendat".
In the PHP API, the parameters are not in it, right?
Is this still planned?

**Comment by Codesleuth** [comment]
Does #8 do what you need?

**Comment by tubssp** [comment]
only partially.

I would find the "retries" parameter very helpful.

Is there a plan when the #8  is merged?
